-- MySQL Script generated by MySQL Workbench
-- Fri Dec 28 14:27:14 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema accountingsystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema accountingsystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `accountingsystem` DEFAULT CHARACTER SET utf8 ;
USE `accountingsystem` ;

-- -----------------------------------------------------
-- Table `accountingsystem`.`balance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingsystem`.`balance` (
  `ID` INT(11) NOT NULL,
  `Profit` DOUBLE NOT NULL,
  `Date` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `accountingsystem`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingsystem`.`item` (
  `ID` INT(11) NOT NULL,
  `Name` VARCHAR(255) NOT NULL,
  `Price` DOUBLE NOT NULL,
  `Amount` INT(11) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `accountingsystem`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingsystem`.`transaction` (
  `ID` INT(11) NOT NULL,
  `Kind` VARCHAR(255) NOT NULL,
  `ItemID` INT(11) NOT NULL,
  `Amount` INT(11) NOT NULL,
  `TotalPrice` DOUBLE NOT NULL,
  `UserID` INT(11) NOT NULL,
  `Time` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `accountingsystem`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accountingsystem`.`user` (
  `ID` INT(11) NOT NULL,
  `Name` VARCHAR(255) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `Kind` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
